### ISSUE TITLE
python setuptools have deprecated easy_install

### ISSUE THREAD

**Issue by hexcoder-** [AFLplusplus/unicornafl_legacy#13]
According to [setuptools](https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html) easy_install is deprecated and in fact on my current Arch Linux it is not present anymore, disabling python-mode here.
The website recommends to use pip instead of easy_install.

Sooner or later this will be a problem for other distros too...

**Comment by domenukk** [comment]
I think it's fine if we stay on setup_tools as long as upstream unicorn does it. Python2.7 has been EOLled also but is still supported. Closing for now :)

**Comment by hexcoder-** [comment]
So i need to escalate it in upstream unicorn.

**Comment by domenukk** [comment]
Feel free to do so, however my bet is, setuptools will stay around for at least another 5-10 years :)

**Comment by hexcoder-** [comment]
I don't mind for setuptools, but easy_install needs to be replaced by something else, so unicornafl can be build in current Linux distros (like Arch Linux). The problem is: it does not build right now.

**Comment by domenukk** [comment]
when running make?
Do you maybe need to `pip3 install -u setuptools`?

**Comment by hexcoder-** [comment]
No, I have current `setuptools`, but `setuptools` does not have `easy_install` anymore which is required.

**Comment by hexcoder-** [comment]
When running the build script.

**Comment by domenukk** [comment]
The build script just does an `import setuptools`, if you have them installed, you should be good to go, see
https://github.com/AFLplusplus/AFLplusplus/blob/d999725de217a0adf4f936954c418ad8c8c3da2a/unicorn_mode/build_unicorn_support.sh#L123

I don't see where `easy_install` would be explicitly used?
We can change the warning of course.

**Comment by hexcoder-** [comment]
sh test-unicorn-mode.sh:
[*] starting afl++ test framework ...
[*] Testing: unicorn_mode
[-] Error: Python setup-tools not found. Run 'sudo apt-get install python-setuptools'.
[*] running afl-fuzz for unicorn_mode (persistent), this will take approx 25 seconds
[+] afl-fuzz is working correctly with unicorn_mode (persistent)
[*] Using python binary 
[-] we cannot test unicorn_mode for python because it is not present
[*] 1 test cases completed.
[-] not all test cases were executed
[+] all tests were successful :-)

**Comment by hexcoder-** [comment]
maybe it is the check in test-unicorn-mode.sh:
`if $PYTHON -c "help('easy_install');" </dev/null | grep -q module ; then`

**Comment by hexcoder-** [comment]
So, how to check for installed setuptools instead?

**Comment by domenukk** [comment]
like this?
https://github.com/AFLplusplus/AFLplusplus/blob/d999725de217a0adf4f936954c418ad8c8c3da2a/unicorn_mode/build_unicorn_support.sh#L123

**Comment by hexcoder-** [comment]
ok, that worked, I fixed it now.
