### ISSUE TITLE
Memory corruption while mapping memory?

### ISSUE THREAD

**Issue by expend20** [AFLplusplus/unicornafl_legacy#20]
Hello! 

I'm trying to get into the project, this means there is a chance I'm doing something in a very wrong way.
But while mapping some chunks into Unicorn's memory layout I'm getting memory corruption:

```rust
use unicornafl::unicorn_const::{ Arch, Mode, Permission };

fn main() {

    let mut uni = unicornafl::Unicorn::new(Arch::X86, Mode::MODE_64, 0)
        .expect("failed to initialize unicorn instance");
    let mut emu = uni.borrow();

    let mems = [
        (0x0007ffe2000, 0x1000),
        (0x03230f4c000, 0x4000),
        (0x03231085000, 0x9000),
        (0x032312fe000, 0x2000),
        (0x032313fe000, 0x2000),
        (0x032314ff000, 0x1000),
        (0x1fcefe10000, 0x10000),
        (0x1fcefe20000, 0x1000),
        (0x1fcefe30000, 0x1d000),
        (0x1fcefe50000, 0x4000),
        (0x1fcefe60000, 0x1000),
        (0x1fcefe70000, 0x2000),
        (0x1fcefe80000, 0xc9000),
        (0x1fceff50000, 0x1000),
    ];

    for (i, &(addr, size)) in mems.iter().enumerate() {
        println!("Mapping {} {:x} {:x}", i, addr, size);
        let r = emu.mem_map(addr, size, Permission::ALL);
        assert_eq!(r, Ok(()));
    }
}
```

Apparently this leads to memory corruption:
```
   Compiling unicornafl v1.1.0 (/home/john/rust-re/unicornafl/bindings/rust)
   Compiling uafl-bug v0.1.0 (/home/john/rust-re/uafl-bug)
    Finished release [optimized] target(s) in 3.18s
     Running `target/release/uafl-bug`
Mapping 0 7ffe2000 1000
Mapping 1 3230f4c000 4000
Mapping 2 3231085000 9000
Mapping 3 32312fe000 2000
Mapping 4 32313fe000 2000
Mapping 5 32314ff000 1000
Mapping 6 1fcefe10000 10000
Mapping 7 1fcefe20000 1000
Mapping 8 1fcefe30000 1d000
Mapping 9 1fcefe50000 4000
Mapping 10 1fcefe60000 1000
Mapping 11 1fcefe70000 2000
Mapping 12 1fcefe80000 c9000
Mapping 13 1fceff50000 1000
corrupted size vs. prev_size while consolidating
Aborted
```
If I continue to add another memory it cat eventually hit another memory corruption, e.g.:
```
double free or corruption (!prev)
Aborted
```

Any thoughts on this?

Thank you!

**Comment by expend20** [comment]
The bug is not reproducible to me on the original Unicorn's master branch (https://github.com/unicorn-engine/unicorn/tree/master/bindings/rust)

**Comment by domenukk** [comment]
Hey,
this is a known bug on upstream unicorn 1.x in the `next` branch, see
https://github.com/unicorn-engine/unicorn/issues/1394
My plan is to move unicornafl to Unicorn 2 soon, but for the time being there is no fix, sorry

**Comment by expend20** [comment]
> Hey, this is a known bug on upstream unicorn 1.x in the `next` branch, see [unicorn-engine#1394](https://github.com/unicorn-engine/unicorn/issues/1394) My plan is to move unicornafl to Unicorn 2 soon, but for the time being there is no fix, sorry

Ah, thank you! Then, let me close this issue
