### ISSUE TITLE
Plans to upgrade to unicorn-2?

### ISSUE THREAD

**Issue by user000543** [AFLplusplus/unicornafl_legacy#21]
Hey, thanks for the great work on this project, its helped me a lot.

I noticed unicorn now has a version2 RC (https://github.com/unicorn-engine/unicorn/releases/tag/2.0.0-rc1) that is based off of QEMU-5 and is much faster. Are you planning on upgrading unicornAFL to that version of unicorn?

Thanks!

**Comment by domenukk** [comment]
It's definitely going to happen.
I started an initial port in the https://github.com/AFLplusplus/unicornafl/tree/afluc2 branch (but it doesn't compile yet).
Also, @wtdecode is pushing to get unicornafl support into upstream unicorn somehow, see https://twitter.com/pwnedmio/status/1452635107492343809?s=20

**Comment by domenukk** [comment]
Please take a look at 
https://github.com/wtdcode/unicorn2afl
We will add rust bindings and move it here eventually.
