### ISSUE TITLE
PowerPC Support

### ISSUE THREAD

**Issue by sucof** [AFLplusplus/unicornafl_legacy#9]
hi, Is it support powerpc?

**Comment by domenukk** [comment]
No, sorry. Upstream unicorn dropped powerpc support recently, I'm sure they had reasons. You can try an older version and see if it runs.

**Comment by domenukk** [comment]
This was the last commit before they removed it officially, feel free to try.
https://github.com/AFLplusplus/unicornafl/commit/b5f9441689d953ceb46acb2e4e3cf8580fe92031

**Comment by domenukk** [comment]
Upstream unicorn now has support for powerpc in this branch:
https://github.com/unicorn-engine/unicorn/tree/next
This should be easy to integrate.

**Comment by domenukk** [comment]
Just merged powerPc support with commit 212110c.
Feel free to test. :)
